### ISSUE TITLE
Error when running Decimer from script

### ISSUE THREAD

**Issue by pythonnewbie3** [Kohulan/DECIMER-Image_Transformer#25] opened 2022-07-20 14:42 UTC
Hi,
I tried to run Decimer2 from my script using: 
from DECIMER import predict_SMILES
image_path = r"C:\Users\........."
SMILES = predict_SMILES(image_path)
print(SMILES)

And I received to following error: 

What can I do?

Downloading trained model to C:\Users\SAWACH\.data\DECIMER-V2
C:\Users\SAWACH\.data\DECIMER-V2\models.zip
done downloading trained model!
Traceback (most recent call last):

  File "C:\Users\SAWACH\Desktop\RoseBoom2.2 Supersloth\untitled0.py", line 2, in <module>
    from DECIMER import predict_SMILES

  File "C:\Users\SAWACH\anaconda3\lib\site-packages\DECIMER\__init__.py", line 33, in <module>
    from .decimer import predict_SMILES

  File "C:\Users\SAWACH\anaconda3\lib\site-packages\DECIMER\decimer.py", line 34, in <module>
    config.download_trained_weights(model_url, default_path)

  File "C:\Users\SAWACH\anaconda3\lib\site-packages\DECIMER\config.py", line 296, in download_trained_weights
    subprocess.run(

  File "C:\Users\SAWACH\anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\SAWACH\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\SAWACH\anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\Users\SAWACH\anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

Decimer1 worked by just installing it with pip.

**Comment by OBrink** [comment] 2022-07-20 15:30
Hey there! 

I have just set up a fresh conda environment on Windows 11 and I cannot reproduce your problem. It appears that DECIMER relies on the command "unzip" to extract the downloaded model files (and you don't have it installed on your system).

It seems that in config.py, line 296ff is causing the problem.:
```
subprocess.run(
            [
                "unzip",
                model_path.as_posix(),
                "-d",
                model_path.parent.as_posix(),
            ]
```


@Kohulan, we should probably unzip the downloaded models using the [Python library zipfile](https://docs.python.org/3/library/zipfile.html) instead of calling a subprocess. 

@pythonnewbie3, Thank you for the bug report! I have three suggestions to make it work for you until replace calling the subprocess with handling the extraction in Python:
- Work with the Linux subsystem for Windows. Here, the command "unzip" can be called by DECIMER as a subprocess without causing trouble.
- You could install the command line command "unzip" which could then be called as a subprocess by DECIMER. A quick Google search yielded [this](http://stahlworks.com/dev/index.php?tool=zipunzip) (I have not tried it as "unzip" already works in my Anaconda Powershell Prompt)
- You could manually extract the downloaded model files

**Comment by pythonnewbie3** [comment] 2022-07-20 18:46
Hi,
thank you for the promt response. How do I extract them manually? What direction to I put them into?

I work on Windows 10 because most of the programs only run ob windows 10. Maybe that's why you can reproduce the bug.
Best regards

**Comment by Kohulan** [comment] 2022-07-21 11:05
Hi @pythonnewbie3 ,

The bug is now fixed if you installed DECIMER from PyPi with the new version it should automatically download the weights to your "Home" Directory.

After downloading the python zip file package should unzip the models to the relevant directory. Let us know if this solves your issue.

**Comment by pythonnewbie3** [comment] 2022-07-21 12:08
Hi @Kohulan,
thank you so much, I just ran a few compounds other structure recognition software could not handle. I am really impressed!

**Comment by Kohulan** [comment] 2022-07-21 12:09
@pythonnewbie3 Great!
I am closing this issue now. Thanks a lot for the bug report 😃

**Closed by Kohulan** 2022-07-21 12:09 UTC
Labels: bug
